### ISSUE TITLE
Add live session tracking, multi-session support and fix various bugs

### ISSUE THREAD

**Issue by coolaj86** [digitalcashdev/DashJoin#4]
- [x] correctly visualize session info
- [x] correct detect, and connect or reconnect to session
- [x] add multi-session support (i.e. for self-test on testnet or faster rounds on mainnet)

Relevant commits (will be squashed later)

- 8ba93f6 feat: show session info
- 28b7ff6 wip: debugging dsq vs dsi
- e6cd10b feat: track open coinjoin sessions
- 630dcfc doc: distinguish between P2P and CoinJoin
- cf2c2b9 feat: proper multiplexing of CJ pools

**Comment by coolaj86** [comment]
@jojobyte Claiming

Address: Xev9KpNTXAmQhyqqgp3KpKf6HTmHKStFrx

Deliverables: See above.

Also, about 2/3rds of the work for these was captured live: https://www.youtube.com/playlist?list=PLF5Va8rgg4DGvvOhHkzaUgkCkwWZa7zh-
